### ISSUE TITLE
Enable HTTPS on Teampeggle.com

### ISSUE THREAD

**Issue by Sunii** [TeamPeggle/TeamPeggle.github.io#10]
Let's get secure!

I've changed the A Records to point to the new github CDN IP's but we are still serving mixed content.

Old A Record 
teampeggle.com.	3600	A	192.30.252.153

New A Records
teampeggle.com.	3600	A	185.199.108.153     							
teampeggle.com.	3600	A	185.199.109.153     							
teampeggle.com.	3600	A	185.199.110.153     	
teampeggle.com.	3600	A	185.199.111.153

I have also removed the custom domain and re-added it to trigger certificate generation.

https://help.github.com/articles/securing-your-github-pages-site-with-https/
https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by imnotjames** [comment]
Gotta secure those credit cards

**Comment by imnotjames** [comment]
I enabled `Enforce HTTPS` and we are now good.
